# Numpy Basics

In [2]:
import numpy as np

In [3]:
arr = np.array([-1, 2, 5], dtype=np.float32)
print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


Numpy arrays can take any n-d dimensions

In [4]:
arr = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.float32)
print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


If numpy array has mixed types, the array's type will be upcast to the highest level type. i.e. int -> float. And numbers -> strings

In [5]:
arr = np.array(["Hayford", 2, 3.0])
print(repr(arr))

array(['Hayford', '2', '3.0'], dtype='<U32')


Numpy arrays are mutable. To create a new object, _copy_ is used.

In [6]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print(f"Array a :{repr(a)}")
c[0] = 5
print(f"Array a: {repr(a)}")

d = b.copy()
d[0] = 6
print(f"Array b: {repr(b)}")

Array a :array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


Casting of an array is done through __*astype*__ function. 

In [7]:
arr = np.array([0, 1, 2])
print(arr.dtype)

arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


To indicate that an index contains no particular value, we use **np.nan** as a placeholder.

In [8]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))
arr = np.array([np.nan, "abc"])
print(repr(arr))

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


If **np.nan** is used in addition to other types, the dtype specified matters

In [9]:
# np.array([np.nan, 1, 2], dtype=np.int32)  # --> cannot convert float NaN to integer
arr = np.array([np.nan, 1, 2], dtype=np.float32)
print(repr(arr))

array([nan,  1.,  2.], dtype=float32)


To represent a huge number, **np.inf** is used

In [10]:
print(np.inf > 1000000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

True
array([inf,  5.])
array([-inf,   1.])


np.inf is of type float.   
The following will cause an error if uncommented out

In [11]:
# np.array([np.inf, 3], dtype=np.int32) # cannot convert float infinity to integer

Similar to range, there is **np.arange** that creates a new array with the values as the range specified

In [12]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4, dtype=np.float32)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1.,  0.,  1.,  2.,  3.], dtype=float32)
array([-1.5,  0.5,  2.5])


**np.linspace** is used to specify the number of elements in the returned array, rather than the step size. Required arguments are: start and end (inclusive). There is optional argument endpoint that if set to *False*, the end is not inclusive. To specify the number of elements, we set *num* keyword argument (has default value 50). 

In [18]:
arr = np.linspace(5, 11)
print(repr(arr))

arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4)

array([ 5.        ,  5.12244898,  5.24489796,  5.36734694,  5.48979592,
        5.6122449 ,  5.73469388,  5.85714286,  5.97959184,  6.10204082,
        6.2244898 ,  6.34693878,  6.46938776,  6.59183673,  6.71428571,
        6.83673469,  6.95918367,  7.08163265,  7.20408163,  7.32653061,
        7.44897959,  7.57142857,  7.69387755,  7.81632653,  7.93877551,
        8.06122449,  8.18367347,  8.30612245,  8.42857143,  8.55102041,
        8.67346939,  8.79591837,  8.91836735,  9.04081633,  9.16326531,
        9.28571429,  9.40816327,  9.53061224,  9.65306122,  9.7755102 ,
        9.89795918, 10.02040816, 10.14285714, 10.26530612, 10.3877551 ,
       10.51020408, 10.63265306, 10.75510204, 10.87755102, 11.        ])
array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])


Numpy arrays can also be reshaped to a different dimension using **np.reshape**, which takes in the array to be reshaped and the new dimensions as required arguments. 

In [23]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print(f"New shape: {reshaped_arr.shape}")

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)


The shape passed in as argument can have -1 in at most one dimension to allow the new shape to contain all the elements of the array;

In [27]:
reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print(f"New shape: {reshaped_arr.shape}")

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


There is also the option to flatten an array to 1D using **flatten** function.

In [28]:
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print(f"arr shape: {arr.shape}")

print(repr(flattened))
print(f"flattened shape: {flattened.shape}")

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


There **np.transpose** to convert arr to a different format and dimensions

In [29]:
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print(f"arr shape: {arr.shape}")

print(repr(transposed))
print(f"transposed shape: {transposed.shape}")

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


**np.transpose** has an optional argument *axes*, which represents the new permutation of the dimensions. The permutation is a list or tuple of integers. 

In [32]:
arr = np.arange(24)
arr = np.reshape(arr, (3 ,4, 2))
transposed = np.transpose(arr, axes=(1, 2, 0))
print(f"arr shape: {arr.shape}")
print(repr(transposed))
print(f"transposed shape: {transposed.shape}")

arr shape: (3, 4, 2)
array([[[ 0,  8, 16],
        [ 1,  9, 17]],

       [[ 2, 10, 18],
        [ 3, 11, 19]],

       [[ 4, 12, 20],
        [ 5, 13, 21]],

       [[ 6, 14, 22],
        [ 7, 15, 23]]])
transposed shape: (4, 2, 3)


Numpy provides the option to have an array fill with solely ones or zeros using **np.zeros** or **np.ones**

In [33]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


We can also create array with zeros or ones with same shape as another array using **np.zeros_like** or **np.ones_like**

In [34]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


## Numpy Math

In [36]:
arr = np.array([[1, 2], [3, 4]])

# Add 1 to every element
print(repr(arr + 1))

# Subtract 1.2 from element values
print(repr(arr - 1.2))

# Double element values 
print(repr(arr * 2))

# Halve element values
print(repr(arr / 2))

# floor or integer division 
print(repr(arr // 2))

# Square each element 
print(repr(arr ** 2))

# square root each element
print(repr(arr ** 0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


It is easy to convert huge dataset with only a few operations

In [37]:
def f2c(temps):
  return (5/9) * (temps - 32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print(f"Celsius: {repr(celsius)}")

Celsius: array([  0., -20., -10., -40.])


NB: Performing arithmetic on numpy arrays *do not change the original array.* A new array is created for the result of the operation. 

## Non-linear functions
e.g. **np.exp** --> performs a base *e* exponential on an array  
     **np.exp2** --> performs a base 2 exponential on an array  
     **np.log** --> performs logarithms using base *e*  
     **np.log2** --> performs logarithms using base 2  
     **np.log10** --> performs logarithms using base 10

In [43]:
arr = np.array([[1, 2], [3, 4]])
print(f"Original arr: {repr(arr)}")

# raise to power of e
print(f"Raising a power of e based on the elements: \n\t\t\t\t{repr(np.exp(arr))}")

print(f"Raising a power of 2 based on the elements: \n\t\t\t\t{repr(np.exp2(arr))}")

arr2 = np.array([[1, 10], [np.e, np.pi]])
print(f"Natural logarithm: \n\t\t\t\t{repr(np.log(arr2))}")
print(f"Base 10 logarithm: \n\t\t\t\t{repr(np.log10(arr2))}")


Original arr: array([[1, 2],
       [3, 4]])
Raising a power of e based on the elements: 
				array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
Raising a power of 2 based on the elements: 
				array([[ 2.,  4.],
       [ 8., 16.]])
Natural logarithm: 
				array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
Base 10 logarithm: 
				array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


**np.power** is used to do a regular power operation with any base. First argument is the base and the second is the power.

In [44]:
arr = np.array([[1, 2], [3, 4]])

print(f"Raise 3 to power of each number in arr: {repr(np.power(3, arr))}")

arr2 = np.array([[10.2, 4], [3, 5]])
print(f"Raise arr2 to power of each number in arr: {repr(np.power(arr2, arr))}")

Raise 3 to power of each number in arr: array([[ 3,  9],
       [27, 81]])
Raise arr2 to power of each number in arr: array([[ 10.2,  16. ],
       [ 27. , 625. ]])


[This documentation](https://numpy.org/doc/stable/reference/routines.math.html) contains a list of the numpy mathematical functions.

## Matrix multiplication

**np.matmul** takes two vector/matrix arrays as input and produces a dot product or matrix multiplication. Dimensions should be valid.

In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])

print(f"Dot product: {np.matmul(arr1, arr2)}")

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(f"Matrix multiplication A3 x A4: {repr(np.matmul(arr3, arr4))}")
print(f"Matrix multiplication A4 x A3: {repr(np.matmul(arr4, arr3))}")

# This causes error: size 3 is different from 2
# print(repr(np.matmul(arr3, arr3)))

Dot product: 27
Matrix multiplication A3 x A4: array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
Matrix multiplication A4 x A3: array([[  4,   4],
       [-11, -10]])
